
// products
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
//side bar

export const OPEN_SIDE_CART = 'OPEN_SIDE_CART';
export const CLOSE_SIDE_CART = 'CLOSE_SIDE_CART';
export const TOGGLE_SIDE_CART = 'TOGGLE_SIDE_CART';
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

//USER 
//Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//LOGUT 
export const LOGOUT = 'LOGOUT';

//USER_ACCOUNT
export const USER_ACCOUNT = 'USER_ACCOUNT';
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS';
export const USER_ACCOUNT_FAIL = 'USER_ACCOUNT_FAIL'